### ISSUE TITLE
 5# Gerar a primeira versão do jogo (Exportar em HTML para leitura)

### ISSUE THREAD

**Issue by lasscampos** [glass-queens/jogoweb#4]

**Comment by Jessica-ps** [comment]
@Fernandaalcione amiga tenta botar a versão HTML aqui

**Comment by Jessica-ps** [comment]
file:///C:/Users/Eliziel/Downloads/teste%20(1)%20(2)%20(1).html

**Comment by Fernandaalcione** [comment]
Em seg., 21 de dez. de 2020 às 12:18, Jessica-ps <notifications@github.com>
escreveu:
